name: Clean Unused Docker Image

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        required: true
        type: boolean
        default: false
      cut_off:
        description: 'Cut off date'
        required: true
        type: string
        default: '90days'
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old unused images
    steps:
      - name: clean tryzealot/zealot images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: tryzealot
          token: ${{ secrets.SECRET_API_TOKEN }}
          image-names: "zealot"
          tag-selection: untagged
          cut-off: ${{ inputs.cut_off }}
          dry-run: ${{ inputs.dry_run }}
      - name: clean tryzealot/codespace images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: tryzealot
          token: ${{ secrets.SECRET_API_TOKEN }}
          image-names: "codespace"
          tag-selection: untagged
          cut-off: ${{ inputs.cut_off }}
          dry-run: ${{ inputs.dry_run }}